version: "3.0"

services:
    php:
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - "8000:8000"
        depends_on:
            - mysql

    mysql:
        image: mysql:8.1 # versão do mysql
        container_name: mysql
        restart: unless-stopped # automatiza o reinicio do container caso o mysql pare de funcionar
        tty: true # Habilita bash para interagir com o container mysql
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD==${DB_PASSWORD}
